### ISSUE TITLE
As a user, I'd like to be able to roll a random number

### ISSUE THREAD

**Issue by adigitalmonk** [adigitalmonk/durendal-bot#46]
Does Discord already support this?

**Comment by dmasterson** [comment]
I don't think it does natively. I've got a implementation but I wasn't sure what the defaults should be. Currently picks a random number between one and six inclusive. Specifying an integer will pick between 1 and the given inclusive. Specifying two integers will pick between the givens inclusive. So the question is if a traditional dice should be the default or not.

**Comment by adigitalmonk** [comment]
I had thoughts to make this work kind of like a dice roller.

E.g., 
1d100 -> roll one 100 sided dice; 
2d20h1 -> roll 2 d20, keep the highest 1;
2d20l1 -> roll 2 d20, keep the lowest 1

I'm not sold on that syntax, just conveying an idea.
