### ISSUE TITLE
As an administrator, I'd like the ability to turn the bot off from chat.

### ISSUE THREAD

**Issue by adigitalmonk** [adigitalmonk/durendal-bot#7]
As an administrator, I'd like the ability to turn the bot off from chat.

**Comment by adigitalmonk** [comment]
I have a way to do this in PR #37 which enables admin commands on the CLI.  We're working on #18 for permissions on how to do this from chat.

**Comment by adigitalmonk** [comment]
This can be done now with the Interface, and #40 has support for doing this.

**Comment by dmasterson** [comment]
Both the Interface and #40 have been merged.
